[package]
name = "pallet-kp"
version = "4.0.0-dev"
description = "Knowledge Power Pallet"
authors = ["CTT DEV <https://>"]
homepage = "https://substrate.io"
license = "Unlicense"
edition.workspace = true
publish = false
repository = "https://"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
parking_lot = "0.12.1"
serde = { version = "1.0.101", features = ["derive"], optional = true }
rand_chacha = { version = "0.3.1", default-features = false }
hex = { version = "0.4", default-features = false }
substrate-fixed = { git = 'https://github.com/encointer/substrate-fixed.git' }

frame-support = { path = "../../../../frame/support", default-features = false }
frame-system = { path = "../../../../frame/system", default-features = false }

sp-core = { path = "../../../../primitives/core", default-features = false }
sp-std = { path = "../../../../primitives/std", default-features = false }
sp-io = { path = "../../../../primitives/io", default-features = false }
sp-runtime = { path = "../../../../primitives/runtime", default-features = false }

frame-benchmarking = { path = "../../../../frame/benchmarking", default-features = false, optional = true }
node-primitives = { path = "../../primitives", default-features = false }

pallet-balances = { path = "../../../../frame/balances", default-features = false }
members = { version = "4.0.0-dev", path = "../members", package = "pallet-members", default-features = false }

[dev-dependencies]


[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
    "hex/std",
    "members/std",
    "node-primitives/std",
    "pallet-balances/std",
	"scale-info/std",
    "serde",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
