[package]
name = "tracking-allocator"
description = "Tracking allocator to control amount of memory consumed by PVF preparation process"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
