[package]
name = "sc-chain-spec"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate chain configurations."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
json-patch = { version = "1.0.0", default-features = false }
memmap2 = "0.5.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.85"
sc-client-api = { path = "../api" }
sc-chain-spec-derive = { path = "derive" }
sc-executor = { path = "../executor" }
sc-executor-common = { path = "../../client/executor/common" }
sp-io = { default-features = false, path = "../../primitives/io" }
sc-network = { path = "../network" }
sc-telemetry = { path = "../telemetry" }
sp-blockchain = { path = "../../primitives/blockchain" }
sp-core = { path = "../../primitives/core" }
sp-genesis-builder = { path = "../../primitives/genesis-builder" }
sp-runtime = { path = "../../primitives/runtime" }
sp-state-machine = { path = "../../primitives/state-machine" }
log = { version = "0.4.17", default-features = false }
array-bytes = { version = "6.1" }

[dev-dependencies]
substrate-test-runtime = { path = "../../test-utils/runtime" }
sp-keyring = { path = "../../primitives/keyring" }
sp-application-crypto = { default-features = false, path = "../../primitives/application-crypto", features = ["serde"]  }
sp-consensus-babe = { default-features = false, path = "../../primitives/consensus/babe", features = ["serde"] }
